// scripts/responses.js

const responses = {
    'hi': 'Hello! How can I help you today?',
    'hello': 'Hello! How can I assist you?',
    'how are you?': 'I\'m just a bot, but I\'m doing well, thanks for asking!',
    'what is 1+1?': 'The answer is 2.',
    'what is your name?': 'I am an AI chatbot created to assist you!',
    'where are you from?': 'I exist in the digital world, here to help you wherever you are.',
    'what can you do?': 'I can chat with you, answer questions, solve math problems, and more! Just ask.',
    'how old are you?': 'I don’t have an age like humans, but I was created to assist with your queries.',
    'what is the weather like?': 'I can’t check the weather right now, but you can look outside or use a weather app!',
    'who is the ceo of tesla?': 'Elon Musk is the CEO of Tesla.',
    'what is the speed of light?': 'The speed of light is approximately 299,792 kilometers per second.',
    'what is the boiling point of water?': 'The boiling point of water is 100°C or 212°F at sea level.',
    'who invented the telephone?': 'The telephone was invented by Alexander Graham Bell.',
    'what is the largest planet in our solar system?': 'The largest planet in our solar system is Jupiter.',
    'who was the first president of the united states?': 'George Washington was the first president of the United States.',
    'what year did the titanic sink?': 'The Titanic sank in 1912.',
    'who wrote romeo and juliet?': 'Romeo and Juliet was written by William Shakespeare.',
    'who was albert einstein?': 'Albert Einstein was a famous physicist known for developing the theory of relativity.',
    'what is the great wall of china?': 'The Great Wall of China is a series of fortifications made of various materials, built along the northern borders of China to protect against invasions.',
    'what is the smallest country in the world?': 'The smallest country in the world is Vatican City.',
    'how many continents are there?': 'There are seven continents: Africa, Antarctica, Asia, Europe, North America, Australia, and South America.',
    'what is the most spoken language in the world?': 'The most spoken language in the world by native speakers is Mandarin Chinese.',
    'what is the longest river in the world?': 'The Nile River is often considered the longest river in the world.',
    'what is the tallest mountain in the world?': 'Mount Everest is the tallest mountain in the world, standing at 8,848 meters (29,029 feet) above sea level.',
    'why did the scarecrow win an award?': 'Because he was outstanding in his field!',
    'why don’t scientists trust atoms?': 'Because they make up everything!',
    'what do you call fake spaghetti?': 'An impasta!',
    'how do you organize a space party?': 'You planet!',
    'why don’t skeletons fight each other?': 'They don’t have the guts!',
    'what do you call cheese that isn’t yours?': 'Nacho cheese!',
    'why did the bicycle fall over?': 'Because it was two-tired!',
    'how do you catch a squirrel?': 'Climb a tree and act like a nut!',
    'why don’t some couples go to the gym?': 'Because some relationships don’t work out!',
    'what’s brown and sticky?': 'A stick!',
    'how was your day?': 'I’m just a bot, so my day is always the same! How was yours?',
    'what do you like to do?': 'I enjoy chatting with you and helping with your questions!',
    'do you have any hobbies?': 'I don’t have hobbies like humans do, but I’m always here to assist you!',
    'what’s your favorite color?': 'As a digital entity, I don’t see colors, but I bet they’re all amazing!',
    'do you like music?': 'I can’t listen to music, but I can help you find information about your favorite songs or artists!',
    'goodbye': 'Goodbye! Have a great day!',
    'see you later': 'See you later! I’ll be here when you need me.',
    'talk to you soon': 'Talk to you soon! Take care.',
    'i have to go': 'No worries, catch you later!',
    'thanks for the chat': 'You’re welcome! It was great chatting with you!',
    'did you know': 'Did you know honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!',
    'tell me something interesting': 'Did you know octopuses have three hearts? Two pump blood to the gills, and one pumps it to the rest of the body!',
    'give me a fun fact': 'Did you know that the Eiffel Tower can be 15 cm taller during the summer? The metal expands in the heat!',
    'surprise me': 'Did you know that a group of flamingos is called a "flamboyance"?',
    'tell me a secret': 'Here’s a secret: I’m always ready to chat, 24/7!',
    'tell me something motivational': 'Believe in yourself! You are capable of amazing things.',
    'give me some inspiration': 'The only limit to our realization of tomorrow is our doubts of today.',
    'i need encouragement': 'Don’t watch the clock; do what it does. Keep going!',
    'can you inspire me?': 'Success is not final, failure is not fatal: It is the courage to continue that counts.',
    'give me a motivational quote': 'The best way to get started is to quit talking and begin doing.',
    'what time is it?': 'I can’t check the current time, but you can always ask your device!',
    'what day is it today?': 'Today is another beautiful day! You can check the date on your device.',
    'what’s the date today?': 'You can find today’s date on your device. I’m just here to chat!',
    'is it morning?': 'Good morning if it is! I hope your day is off to a great start.',
    'is it afternoon?': 'Good afternoon! How’s your day going so far?',
    'who made you?':'the web developer "m-veloper"',
    'yo':'yo,whats up?',
};